<?

if (!isset($_SESSION["db_server"])){
	
	if ($_GET["stage"]=="create"){
		// session variables were not held
	
	}
	
	$html .= "<table>"
		."<tr><td>
	
} else {

}

// Database Creation SQL
$sql = "CREATE TABLE `cms_AuditTrail` (`nAuditTrailId` bigint(20) NOT NULL auto_increment, `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `nUserId` bigint(20) NOT NULL default '0', `cPage` varchar(255) NOT NULL default '', `cData` mediumtext NOT NULL, `cIPAddress` varchar(20) NOT NULL default '', `cSessionId` varchar(30) NOT NULL default '', PRIMARY KEY (`nAuditTrailId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Content` (`nContentId` bigint(20) NOT NULL auto_increment, `cContentKey` varchar(50) NOT NULL default '', `nTemplateId` bigint(20) NOT NULL default '0', `cFunction` varchar(50) NOT NULL default '', `nContentTypeId` bigint(20) NOT NULL default '0', `cTitle` varchar(80) NOT NULL default '', `cFile` varchar(255) NOT NULL default '', `cBody` mediumtext NOT NULL, `cApproved` char(1) NOT NULL default '', `dStart` datetime NOT NULL default '0000-00-00 00:00:00', `dEnd` datetime NOT NULL default '0000-00-00 00:00:00', `nUserAdded` bigint(20) NOT NULL default '0', `nUserEdited` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`nContentId`), KEY `cContentKey` (`cContentKey`), KEY `nTemplateId` (`nTemplateId`), KEY `nContentTypeId` (`nContentTypeId`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_ContentData` (`nContentDataId` bigint(20) NOT NULL auto_increment, `nContentId` bigint(20) NOT NULL default '0', `nPropertyId` bigint(20) NOT NULL default '0', `nDataInt` int(11) NOT NULL default '0', `nDataBigInt` bigint(20) NOT NULL default '0', `dDataDate` datetime NOT NULL default '0000-00-00 00:00:00', `bDataBoolean` int(11) NOT NULL default '0', `nDataFloat` float NOT NULL default '0', `cDataVarchar` varchar(255) NOT NULL default '', `cDataMediumText` mediumtext NOT NULL, `bDataBlob` blob NOT NULL, PRIMARY KEY (`nContentDataId`), KEY `nContentId` (`nContentId`), KEY `nPropertyId` (`nPropertyId`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_ContentSecurity` (`nContentSecurityId` bigint(20) NOT NULL auto_increment, `nUserTypeId` bigint(20) NOT NULL default '0', `nContentTypeId` bigint(20) NOT NULL default '0', `cView` char(1) NOT NULL default '', `cAdd` char(1) NOT NULL default '', `cEdit` char(1) NOT NULL default '', `cDelete` char(1) NOT NULL default '', `cApprove` char(1) NOT NULL default '', PRIMARY KEY (`nContentSecurityId`), KEY `nUserTypeId` (`nUserTypeId`), KEY `nContentTypeId` (`nContentTypeId`), KEY `cView` (`cView`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_ContentType` (`nContentTypeId` bigint(20) NOT NULL auto_increment, `cContentTypeName` varchar(50) NOT NULL default '', `cFunction` varchar(50) NOT NULL default '', `cFile` varchar(255) NOT NULL default '', `cApprovalRequired` char(1) NOT NULL default '', PRIMARY KEY (`nContentTypeId`), KEY `cApprovalRequired` (`cApprovalRequired`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_ContentTypeProperties` (`nContentTypePropertyId` bigint(20) NOT NULL auto_increment, `nContentTypeId` bigint(20) NOT NULL default '0', `cPropertyName` varchar(255) NOT NULL default '', `cPropertyDescription` varchar(255) NOT NULL default '', `cDataType` varchar(20) NOT NULL default '', `nSortIndex` int(11) NOT NULL default '0', `bMandatory` int(11) NOT NULL default '0', `bHidden` int(11) NOT NULL default '0', `cInputMask` varchar(255) NOT NULL default '', `bUnique` int(11) NOT NULL default '0', PRIMARY KEY (`nContentTypePropertyId`), KEY `nContentTypeId` (`nContentTypeId`), KEY `cDataType` (`cDataType`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Document` (`nDocumentId` bigint(20) NOT NULL auto_increment, `nDocumentTypeId` bigint(20) NOT NULL default '0', `nParentId` bigint(20) NOT NULL default '0', `nVersion` int(11) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', `nAddedBy` bigint(20) NOT NULL default '0', `nEditedBy` bigint(20) NOT NULL default '0', `nRepositoryId` bigint(20) NOT NULL default '0', `cFilename` varchar(255) NOT NULL default '', `cOriginalFilename` varchar(255) NOT NULL default '', `nFilesize` bigint(20) NOT NULL default '0', `cFullText` longtext NOT NULL, PRIMARY KEY (`nDocumentId`), KEY `nDocumentTypeId` (`nDocumentTypeId`), FULLTEXT KEY `cFullText` (`cFullText`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_DocumentData` (`nDocumentDataId` bigint(20) NOT NULL auto_increment, `nDocumentId` bigint(20) NOT NULL default '0', `nPropertyId` bigint(20) NOT NULL default '0', `nDataInt` int(11) NOT NULL default '0', `nDataBigInt` bigint(20) NOT NULL default '0', `dDataDate` datetime NOT NULL default '0000-00-00 00:00:00', `bDataBoolean` int(11) NOT NULL default '0', `nDataFloat` float NOT NULL default '0', `cDataVarchar` varchar(255) NOT NULL default '', `cDataMediumText` mediumtext NOT NULL, `bDataBlob` blob NOT NULL, PRIMARY KEY (`nDocumentDataId`), KEY `nDocumentId` (`nDocumentId`), KEY `nPropertyId` (`nPropertyId`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_DocumentType` (`nDocumentTypeId` bigint(20) NOT NULL auto_increment, `cName` varchar(255) NOT NULL default '', `cDescription` mediumtext NOT NULL, `nRepositoryId` bigint(20) NOT NULL default '0', PRIMARY KEY (`nDocumentTypeId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_DocumentTypeProperties` (`nDocumentTypePropertyId` bigint(20) NOT NULL auto_increment, `nDocumentTypeId` bigint(20) NOT NULL default '0', `cPropertyName` varchar(255) NOT NULL default '', `cPropertyDescription` varchar(255) NOT NULL default '', `cDataType` varchar(20) NOT NULL default '', `nSortIndex` int(11) NOT NULL default '0', `bMandatory` int(11) NOT NULL default '0', `bHidden` int(11) NOT NULL default '0', `cInputMask` varchar(255) NOT NULL default '', `bUnique` int(11) NOT NULL default '0', PRIMARY KEY (`nDocumentTypePropertyId`), KEY `nDocumentTypeId` (`nDocumentTypeId`), KEY `cDataType` (`cDataType`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_DocumentTypeSecurity` (`nDocumentTypeSecurityId` bigint(20) NOT NULL auto_increment, `nDocumentTypeId` bigint(20) NOT NULL default '0', `nUserTypeId` bigint(20) NOT NULL default '0', `cView` char(1) NOT NULL default '0', `cAdd` char(1) NOT NULL default '0', `cEdit` char(1) NOT NULL default '0', `cDelete` char(1) NOT NULL default '0', `cReplace` char(1) NOT NULL default '0', PRIMARY KEY (`nDocumentTypeSecurityId`), KEY `nDocumentTypeId` (`nDocumentTypeId`), KEY `nUserTypeId` (`nUserTypeId`), KEY `cView` (`cView`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_MenuItems` (`nMenuItemId` bigint(20) NOT NULL auto_increment, `nPageId` bigint(20) NOT NULL default '0', `nIndex` bigint(20) NOT NULL default '0', `nLinkedPageId` bigint(20) NOT NULL default '0', `cSection` varchar(50) NOT NULL default '', `cTitle` varchar(80) NOT NULL default '', `cCaption` mediumtext NOT NULL, `nUserAdded` bigint(20) NOT NULL default '0', `nUserEdited` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`nMenuItemId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_PageContent` (`nPageContentId` bigint(20) NOT NULL auto_increment, `nPageId` bigint(20) NOT NULL default '0', `cContentKey` varchar(50) NOT NULL default '0', `nTemplateId` bigint(20) NOT NULL default '0', `nTemplateElementId` tinyint(4) NOT NULL default '0', `nIndex` bigint(20) NOT NULL default '0', `nUserAdded` bigint(20) NOT NULL default '0', `nUserEdited` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`nPageContentId`), KEY `nPageId` (`nPageId`), KEY `cContentKey` (`cContentKey`), KEY `nTemplateId` (`nTemplateId`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_PageData` (`nPageDataId` bigint(20) NOT NULL auto_increment, `nPageId` bigint(20) NOT NULL default '0', `nPropertyId` bigint(20) NOT NULL default '0', `nDataInt` int(11) NOT NULL default '0', `nDataBigInt` bigint(20) NOT NULL default '0', `dDataDate` datetime NOT NULL default '0000-00-00 00:00:00', `bDataBoolean` int(11) NOT NULL default '0', `nDataFloat` float NOT NULL default '0', `cDataVarchar` varchar(255) NOT NULL default '', `cDataMediumText` mediumtext NOT NULL, `bDataBlob` blob NOT NULL, PRIMARY KEY (`nPageDataId`), KEY `nPageId` (`nPageId`), KEY `nPropertyId` (`nPropertyId`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_PageSecurity` (`nPageSecurityId` bigint(20) NOT NULL auto_increment, `nUserTypeId` bigint(20) NOT NULL default '0', `nPageTypeId` bigint(20) NOT NULL default '0', `cView` char(1) NOT NULL default '', `cAdd` char(1) NOT NULL default '', `cEdit` char(1) NOT NULL default '', `cDelete` char(1) NOT NULL default '', `cApprove` char(1) NOT NULL default '', PRIMARY KEY (`nPageSecurityId`), KEY `nUserTypeId` (`nUserTypeId`), KEY `nPageTypeId` (`nPageTypeId`), KEY `cView` (`cView`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_PageType` (`nPageTypeId` bigint(20) NOT NULL auto_increment, `cPageTypeName` varchar(50) NOT NULL default '', PRIMARY KEY (`nPageTypeId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_PageTypeProperties` (`nPageTypePropertyId` bigint(20) NOT NULL auto_increment, `nPageTypeId` bigint(20) NOT NULL default '0', `cPropertyName` varchar(255) NOT NULL default '', `cPropertyDescription` varchar(255) NOT NULL default '', `cDataType` varchar(20) NOT NULL default '', `nSortIndex` int(11) NOT NULL default '0', `bMandatory` int(11) NOT NULL default '0', `bHidden` int(11) NOT NULL default '0', `cInputMask` varchar(255) NOT NULL default '', `bUnique` int(11) NOT NULL default '0', PRIMARY KEY (`nPageTypePropertyId`), KEY `nPageTypeId` (`nPageTypeId`), KEY `cDataType` (`cDataType`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Pages` (`nPageId` bigint(20) NOT NULL auto_increment, `nPageTypeId` bigint(20) NOT NULL default '0', `cPageKey` varchar(64) NOT NULL default '', `cTitle` varchar(80) NOT NULL default '', `cNotes` mediumtext NOT NULL, `nTemplateId` bigint(20) NOT NULL default '0', `nUserAdded` bigint(20) NOT NULL default '0', `nUserEdited` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', `cCache` char(1) NOT NULL default '', `cApproved` char(1) NOT NULL default '', PRIMARY KEY (`nPageId`), KEY `nPageTypeId` (`nPageTypeId`), KEY `cPageKey` (`cPageKey`), KEY `nTemplateId` (`nTemplateId`), KEY `cApproved` (`cApproved`) ) TYPE=MyISAM PACK_KEYS=0;";
$sql .= "\nCREATE TABLE `cms_Repository` (`nRepositoryId` bigint(20) NOT NULL auto_increment, `cPath` varchar(255) NOT NULL default '', PRIMARY KEY (`nRepositoryId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Statistics` (`nStatisticId` bigint(20) NOT NULL auto_increment, `nUserId` bigint(20) NOT NULL default '0', `cPageKey` tinytext NOT NULL, `dView` datetime NOT NULL default '0000-00-00 00:00:00', `cIPAddress` tinytext NOT NULL, `cSessionId` tinytext NOT NULL, PRIMARY KEY (`nStatisticId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Templates` (`nTemplateId` bigint(20) NOT NULL auto_increment, `cType` varchar(16) NOT NULL default '', `cTitle` varchar(30) NOT NULL default '', `cTemplate` mediumtext NOT NULL, `nVersion` bigint(20) NOT NULL default '0', `nUserAdded` bigint(20) NOT NULL default '0', `nUserEdited` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`nTemplateId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_UserType` (`nUserTypeId` bigint(20) NOT NULL auto_increment, `cUserTypeName` varchar(50) NOT NULL default '', PRIMARY KEY (`nUserTypeId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_UserTypeMember` (`nUserTypeMemberId` bigint(20) NOT NULL auto_increment, `nUserId` bigint(20) NOT NULL default '0', `nUserTypeId` bigint(20) NOT NULL default '0', PRIMARY KEY (`nUserTypeMemberId`), KEY `nUserId` (`nUserId`), KEY `nUserTypeId` (`nUserTypeId`) ) TYPE=MyISAM;";
$sql .= "\nCREATE TABLE `cms_Users` (`nUserId` bigint(20) NOT NULL auto_increment, `cUsername` varchar(20) NOT NULL default '', `cPassword` varchar(255) NOT NULL default '', `cEMailAddress` varchar(50) NOT NULL default '', `cAdmin` char(1) NOT NULL default '', `nUserAdded` bigint(20) NOT NULL default '0', `dAdded` datetime NOT NULL default '0000-00-00 00:00:00', `nUserEdited` bigint(20) NOT NULL default '0', `dEdited` datetime NOT NULL default '0000-00-00 00:00:00', `dLastLogon` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`nUserId`) ) TYPE=MyISAM;";

$result = mysql_query($sql,$con);


?>